name: trojan_pro_client
description: Desktop-first, mobile-ready client shell for Trojan-Pro.
publish_to: "none"
version: 1.4.0-beta.4+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  window_manager: ^0.5.1
  tray_manager:
    path: third_party/tray_manager_linux_fallback

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tray/tray_icon.png
    - assets/tray/tray_icon.ico
